### ISSUE TITLE
非前端码猿求问如何添加点击事件和点击改变动作和对话弹出？

### ISSUE THREAD

**Issue by erikaemma** [52cik/bilibili-haruna#3]
就是bilibili直播间右边的娘君，点击有动作，偶尔还会有对话框出来

**Comment by erikaemma** [comment]
另外想问一下up是从头做的还是从官网爬出来的？我试着用chrome查看直播间页面的源码可惜是“出错啦”

**Comment by 52cik** [comment]
从B站爬取的 live2D 模型，只是模型，live2D 技术是日本人发明的。  
爬虫源码在这 <https://github.com/52cik/bilibili-haruna/blob/master/fetch.js>

看板娘的功能，是他们自己开发的，这个你也可以自定义开发，做任意事情。  
比如，我在公司内网做了弹幕留言的功能。。
